baseURL = "http://seansullivan.ai/physci-70"
languageCode = "en-us"
title = "PHYSCI 70: Digital Fabrication"
theme = "pixyll"
relativeURLs = true

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false

[params]
  mainSections = ["post"]
  paginate = 15
